### ISSUE TITLE
通过HttpParamModel接口无法传参?

### ISSUE THREAD

**Issue by bf3400** [litesuits/android-lite-http#12]
参考: https://zybuluo.com/liter/note/187568 (1. 简单参数 HttpParamModel)
版本: lite-http-2.1.5.jar
继承HttpRichParamModel方式调试正常...
但是通过以下方式请求时, 发现日志中没有输出请求参数!!!
        LiteHttp liteHttp = LiteHttp.newApacheHttpClient(null);
        liteHttp.getConfig().setDebugged(true);
        liteHttp.executeAsync(new JsonRequest<ApiModel>(new Goods(1, 0), ApiModel.class));
//LOG
 I/LiteHttp: lite http request: http://sgarss.com:8080/FruitLover/fruitlover/api/goods? , tag: null , method: Get , cache mode: null , thread ID: 7536 , thread name: lite-1
//param参数page和type没有输出...服务端也没有收到请求参数

/////////////////////////附加代码1
    @HttpUri("http://sgarss.com:8080/FruitLover/fruitlover/api/goods")
    public static class Goods implements HttpParamModel {
        public Integer page;
        public Integer type;
        public Goods(Integer page, Integer type) {
            this.page = page;
            this.type = type;
        }
    }

//////////////////////附加代码2
public final class ApiModel {
    public Integer stateCode;
    public String message;
    public String result;
    public boolean isSuccess() {
        return stateCode == 200;
    }
}

**Comment by bf3400** [comment]
服务端也没有收到请求参数

**Comment by bf3400** [comment]
https://zybuluo.com/liter/note/186565

// HttpRichParamModel 如果json是[....]一个数组 也会抛异常
    protected T data; 

////////////////////
    {
        "api": "com.xx.get.userinfo",
        "v": "1.0",
        "result": {
            "code": 200,
            "message": "success"
        },
        "data": [1,2,3]
    }

**Comment by litesuits** [comment]
public class User extends ApiModel<ArrayList<Integer>> {
    // 泛型设置：定义一个公共静态内部类（也可以定义外部类）
}

即可。

**Comment by litesuits** [comment]
public class User extends ApiModel<ArrayList<String>> {
    //  data的泛型一定要和json数据结构保持一致才行。
}

这样即可。

**Comment by litesuits** [comment]
随时可调用 response.printInfo(); 打印信息；注意异常日志

**Comment by bf3400** [comment]
我使用的是fastjson

**Comment by bf3400** [comment]
实现HttpParamModel接口, 参数没有传过去?

**Comment by litesuits** [comment]
不用parseArray，parse整个object。需要看你的代码，加QQ群47357508，找我（群主）细聊
