### ISSUE TITLE
Cookie refected

### ISSUE THREAD

**Issue by shuleihen** [litesuits/android-lite-http#16]
Cookie rejected: "BasicClientCookie[version=0,name=_da_ntes_uid,domain=xxxx,path=/,expiry=Thu Jan 05 09:44:27 GMT+08:00 2017]".

Server Reject Client Exception (服务器拒绝或无法提供服务), code: 400, Bad Request

请问cookie如何设置？

**Comment by litesuits** [comment]
cookie在header中添加即可，request.addHeader或者在litehttp.getConfig()里设置公共header

**Comment by shuleihen** [comment]
这里的cookie是服务器送过来的，不是可以自动写到cookie吗，现在好像是没有权限，如何设置cookie策略
