### ISSUE TITLE
如果想把json解析这块用fastjson来做该怎么操作？

### ISSUE THREAD

**Issue by jbasttdi** [litesuits/android-lite-http#2]
我们项目中json解析用了fastjson这个lib库，解析json的速度是挺快的，如果想把你这个框架中的json解析换成fastjson来做，不知该怎么操作。谢谢了！！

**Comment by litesuits** [comment]
LiteHttp对外和对内都抽象出了Json处理（主要是json和对象互转）方法，仅需要替换实现即可。
具体方法：
1. 写一个简单拓展类：FastjsonImpl替换GsonImpl
2. Json.get()方法中返回new FastjsonImpl()
即可完成全局json解析框架的替换。
