### ISSUE TITLE
网络请求能换成HttpUrlConnection吗？

### ISSUE THREAD

**Issue by winter-jia** [litesuits/android-lite-http#20]
我看了下源码好像网络请求用的HttpClient，实际使用中发现会有比较小的概率下会出现网络无任何返回的情况，不知道是不是因为这个原因，现在android不是已经都废弃httpclient了吗，是不是可以考虑下

**Comment by litesuits** [comment]
现在是最新的 litehttp 3.0的版本，是HttpUrlconnection实现的。
Apache的Client实现已经剥离出来，如需使用可按需采用。
