### ISSUE TITLE
android studio 提示HttpCacheExpire.class重复

### ISSUE THREAD

**Issue by lyx32** [litesuits/android-lite-http#22]
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/litesuits/http/annotation/HttpCacheExpire.class

这个要怎么处理啊？弄的头都大了

**Comment by lyx32** [comment]
我发现问题了，
原来在我引用的一个库里面，还有一个http-lite的jar

**Comment by litesuits** [comment]
ok
