### ISSUE TITLE
如何设置cookie？

### ISSUE THREAD

**Issue by yanglinglong1** [litesuits/android-lite-http#6]

**Comment by litesuits** [comment]
call setHeader() Methods.

**Comment by amervelic** [comment]
use PersistentHttpCookieStore. Add this class to Util folder in the source code LiteHttp, and later in the Application class of your application:

  public void setCookieHandler (Context context) {
         CookieManager cookieManager = new CookieManager (new PersistentHttpCookieStore (context), CookiePolicy.ACCEPT_ALL);
         CookieHandler.setDefault (cookieManager);
     }


@Override
     public void onCreate () {
         super.onCreate ();
         setCookieHandler (getApplicationContext ());
         initLiteHttp ();


     }
